### PR TITLE
FIX #17: Short URL doesn't redirect to long URL in production (WMTL)

### LINKED ISSUE #17: Short URL doesn't redirect to long URL in production (WMTL)
After shortening URL in production: https://tools.wmflabs.org/durl-shortener/shortener.php, the short URL doesn't redirect to the long URL. NOTE: however, this works in localhost, so some debugging needs to be done to figure out why it's not working in production / test server.

### PR DESCRIPTION
**Pull request by GSokol**

### CODE REVIEW

**Review by xSavitar — COMMENTED** [review]
Thanks so much for the patch @GSokol. I already fixed the issue this morning. It's in production already, you can check it out. Sorry I didn't close the issue.

**Comment by xSavitar** [comment]
You can pull to get the latest codes from master and check the project out. It still has some improvements to be done on it. Feel free to create issues. Also, I will close this PR but please feel free to create issues and work on them and we will review your PRs. 👍

**Comment by GSokol** [comment]
@ch3nkula but on production your code still returns `localhost:3000/shortener.php/zdjmmwiy` and, it seems to me, that writes it to DB. But as you wish...

**Comment by xSavitar** [comment]
Hold on, that could be a different issue. Let me just quickly check that now and I will get back to you. Thanks for reporting this.

**Comment by xSavitar** [comment]
Just double checked and you are right! It returns a wrong hostname with the short URL. Can you create an issue for that? Thanks so much for reporting. And you can work on it as well :).

**Comment by GSokol** [comment]
Here is it! https://github.com/ch3nkula/url-shortener/issues/26

**Pull request closed without merging**
